services:

  redis:
    container_name: rate-limiter-redis
    image: redis:7.2.4-alpine3.19
    env_file:
      - path: ./.env
        required: true
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    networks:
      - default

  k6:
    container_name: rate-limiter-k6
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    volumes:
      - ../../scripts/k6/scenarios:/scripts
    networks:
      - default
    environment:
      - K6_WEB_DASHBOARD=true

  api:
    container_name: rate-limiter-api
    build:
      context: ../../
      dockerfile: ./deployments/docker-compose/Dockerfile
    env_file:
      - path: ./.env
        required: true
    ports:
      - "${APP_PORT}:${APP_PORT}"    
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - default
    depends_on:
      - redis
      - k6   

volumes:
  redis-data:


networks:
  default:
